language: c

matrix:
  include:
  - os: linux
    dist: precise
  - os: linux
    dist: trusty
  - os: osx

install: true
cache:
  directories:
  - test/test_suite

script:
- ./build
- ./libbuild
- cd test
- ./download_suite
- ./build
- DYLD_PRINT_LIBRARIES=1 DYLD_PRINT_LIBRARIES_POST_LAUNCH=1
  DYLD_PRINT_RPATHS=1 LD_DEBUG=libs ./oppai_test
- wc -c ./oppai_test
- LDFLAGS="-loppai" ./build -L..
- LD_LIBRARY_PATH=.. DYLD_LIBRARY_PATH=..
  DYLD_PRINT_LIBRARIES=1 DYLD_PRINT_LIBRARIES_POST_LAUNCH=1
  DYLD_PRINT_RPATHS=1 LD_DEBUG=libs ./oppai_test
- wc -c ./oppai_test
